export {default as Group} from "./Group";
export {default as EditGroup} from "./Group/EditGroup";
export {default as User} from "./User";
export {default as EditUser} from "./User/EditUser";
export {default as Subject} from "./Subject";
export {default as EditSubject} from "./Subject/EditSubject";
export {default as Student} from "./Student";
export {default as EditStudent} from "./Student/EditSudent";
export {default as Teacher} from "./Teacher";
export {default as EditTeacher} from "./Teacher/EditTeacher";
export {default as DashboardHome} from "./Dashboard.jsx"
export {default as Resources} from "./Resources"
export {default as UploadResoursec} from  "./Resources/Upload"
